---
- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ruby-full
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libpq-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libffi-dev
    - nodejs
    - libpq-dev
  sudo: yes

- name: download specified ruby version
  get_url:
    url: "http://ftp.ruby-lang.org/pub/ruby/{{ ruby_version |  }}/ruby-{{ ruby_version }}.tar.gz"
    dest: /home/vagrant/ruby2.3.3.tar.gz
    mode: 0644
    owner: vagrant
    group: vagrant
  sudo: yes
    
- file:
    path: "/home/vagrant/ruby2.3.3"
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant
  sudo: yes

- name: unpack ruby2.3.3
  unarchive:
    src: /home/vagrant/ruby2.3.3.tar.gz
    dest: /home/vagrant
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: install ruby2.3.3
  command: ./configure
  args:
    chdir: /home/vagrant/ruby-2.3.3/

- make:
    chdir: /home/vagrant/ruby-2.3.3

- name: Install ruby2.3.3
  make:
    chdir: /home/vagrant/ruby-2.3.3
    target: install
  sudo: yes

- name: install bundler
  command: gem install bundler
  sudo: yes

- name: install rails
  command: gem install rails -v 5.0.0.1
  sudo: yes

- name: clone repo
  git:
    repo: "{{ rails_git_repo }}"
    dest: /home/vagrant/learn-rails

- name: Remove rubyversion from Gemfiles
  lineinfile:
    dest: "/home/vagrant/learn-rails/Gemfile"
    regexp: "ruby '.*'"
    line: "ruby '2.3.3'"
    backup: no

- name: Get dependencies for repo.
  command: bundle install
  args:
    chdir: /home/vagrant/learn-rails

- name: Start aplication
  shell: nohup rails server --binding=0.0.0.0 --port=3000 >> /tmp/rails.log 2>&1 &
  args:
    chdir: /home/vagrant/learn-rails

