---
- apt_repository:
    repo: ppa:brightbox/ruby-ng
    state: present
  sudo: yes

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ruby2.3
    - ruby2.3-dev
    - zlib1g-dev
    - sqlite3
    - libsqlite3-dev
    - nodejs
    - libpq-dev
  sudo: yes
  
# - name: correct ruby version selected
#   alternatives:
#     name: ruby
#     path: /usr/bin/ruby2.2

- name: Update gem
  command: gem update --system 
  args:
    chdir: /home/vagrant
  sudo: yes
  
# - name: Install Rails
#   gem:
#     name: rails
#     state: present
#     user_install: yes
#     include_dependencies: yes
#   sudo: yes
#   tags: installruby

- name: Install gems
  command: gem install "{{ item }}"
  with_items:
    - rails
    - bundler
  sudo: yes

- file:
    path: "{{ rails_git_clone_path }}"
    state: directory
    mode: 0755
    owner: tinkerware
    group: tinkerware
  sudo: yes

- name: Create new blog
  command: rails new blog
  args:
    chdir: "{{ rails_git_clone_path }}"
    creates: "{{ rails_git_clone_path }}/blog"
  when: rails_repos is undefined
  sudo: yes
  sudo_user: tinkerware
  
- name: Clone rails repo
  git:
    repo="{{ item.value.name }}"
    dest="{{ rails_git_clone_path }}/{{ item.value.name | basename }}"
    accept_hostkey=yes
    key_file="{{ rails_git_key_path | default(no) }}"
    version="{{ item.value.branch }}"
  with_dict: "{{ rails_repos | default({}) }}"
  when: rails_repos is defined
  sudo: yes
  sudo_user: tinkerware  

- name: Get blog dependencies
  shell: bundle install
  args:
    chdir: "{{ rails_git_clone_path }}/blog"
  when: rails_repos is undefined  
  sudo: yes
  sudo_user: tinkerware

- name: Start blog
  shell: nohup rails server --binding=0.0.0.0 --port=3000 >> /tmp/rails.log 2>&1 &
  args:
    chdir: "{{ rails_git_clone_path }}/blog"
  when: rails_repos is undefined
  sudo: yes
  sudo_user: tinkerware

- name: Remove rubyversion from Gemfiles
  lineinfile:
    dest: "{{ rails_git_clone_path }}/{{ item.value.name | basename }}/Gemfile"
    regexp: "ruby '.*'"
    line: "ruby '2.3.3'"
    backup: no
  with_dict: "{{ rails_repos | default({}) }}"
  when: rails_repos is defined
  sudo: yes
  sudo_user: tinkerware      

- name: Get apps dependencies
  shell: bundle install --path vendor/bundle
  args:
    chdir: "{{ rails_git_clone_path }}/{{ item.value.name | basename }}"
  with_dict: "{{ rails_repos | default({}) }}"
  when: rails_repos is defined  
  sudo: yes
  sudo_user: tinkerware
  
- name: Start apps
  shell: nohup rails server --binding=0.0.0.0 --port="{{ item.value.port | default(3000) }}" >> /tmp/rails.log 2>&1 &
  args:
    chdir: "{{ rails_git_clone_path }}/{{ item.value.name | basename }}"
  with_dict: "{{ rails_repos | default({}) }}"
  when: rails_repos is defined  
  tags: run_rails
  sudo: yes
  sudo_user: tinkerware
