---
- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ruby-full
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libpq-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libffi-dev
    - nodejs
    - libpq-dev
  sudo: yes

- name: download specified ruby version
  get_url:
    url: "http://ftp.ruby-lang.org/pub/ruby/{{ rails_ruby_version | regex_replace('(^\\d.\\d?).*', '\\1') }}/ruby-{{ rails_ruby_version }}.tar.gz"
    dest: "{{ rails_ruby_package }}"
    mode: 0644
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: unpack new ruby version
  unarchive:
    src: "{{ rails_ruby_package }}"
    dest: "{{ lookup('env','HOME') }}"
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
  sudo: yes

- name: install new ruby version
  command: ./configure
  args:
    chdir: "{{ rails_ruby_version_path }}"
  sudo: yes
  sudo_user: "{{ server_user }}"

- make:
    chdir: "{{ rails_ruby_version_path }}"
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Install new ruby version
  make:
    chdir: "{{ rails_ruby_version_path }}"
    target: install
  sudo: yes

- name: install bundler
  command: gem install bundler
  sudo: yes

- name: install rails
  command: "gem install rails -v {{ rails_rails_version }}"
  sudo: yes

- name: Create destination folder for repo
  file:
    path: /opt/tinker/shared_files/rails_project
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: 0755
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: clone repo
  git:
    repo: "{{ item.value.name }}"
    dest: "{{ rails_repos_path }}/{{ item.value.name | basename }}"
    version: "{{ item.value.version }}"
    accept_hostkey: yes
    recursive: yes
    update: yes
  sudo: yes
  sudo_user: "{{ server_user }}"
  with_dict: "{{ rails_git_repos }}"
  ignore_errors: yes

- name: remove rubyversion from Gemfiles
  lineinfile:
    dest: "{{ rails_repos_path }}/{{ item.value.name | basename }}/Gemfile"
    regexp: "ruby '.*'"
    line: 'ruby "{{ rails_ruby_version }}"'
    backup: no
  sudo: yes
  sudo_user: "{{ server_user }}"
  with_dict: "{{ rails_git_repos }}"

- name: Get dependencies for repo.
  shell: bundle install
  args:
    chdir: "{{ rails_repos_path }}/{{ item.value.name | basename }}"
  sudo: yes
  #sudo_user: "{{ server_user }}"
  with_dict: "{{ rails_git_repos }}"

- name: Start aplication
  shell: "nohup rails server --binding={{ rails_binding_ip }} --port={{ item.value.port }} >> /tmp/rails.log 2>&1 &"
  args:
    chdir: "{{ rails_repos_path }}/{{ item.value.name | basename }}"
  sudo: yes
  sudo_user: "{{ server_user }}"
  with_dict: "{{ rails_git_repos }}"
